spring:
  datasource:
    url: jdbc:postgresql://localhost/invoicedb
    username: invoice
    password: FvKmDaHdz6Mby9aL43kZ
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true